version: 2

updates:
  - package-ecosystem: npm
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Asia/Taipei
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore
      include: scope
    groups:
      npm-minor-and-patch:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Asia/Taipei
    commit-message:
      prefix: ci
      include: scope
    groups:
      actions:
        patterns: ["*"]
