// 把工作區的改動以 GitHub GraphQL createCommitOnBranch 提交，讓 GitHub 代為簽章。
//
// 為什麼不用 git push：Action 內 git push 出去的 commit 是未簽章的，違反 AGENTS.md
// 「commit 必須 GPG 簽章」。走 createCommitOnBranch 由 GitHub 以自家金鑰簽，分支上顯示
// Verified，也不必把任何私鑰交給 CI。
//
// 用法：node scripts/commit_signed.mjs
//   GITHUB_TOKEN   必填，需 contents: write
//   REPO           選填，預設 NTUST-OpenSource/freshman
//   BRANCH         選填，預設 dev
//   COMMIT_TITLE   選填，commit 標題
//   COMMIT_BODY    選填，commit 內文

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';

const REPO = process.env.REPO || 'NTUST-OpenSource/freshman';
const BRANCH = process.env.BRANCH || 'dev';
const TOKEN = process.env.GITHUB_TOKEN;
const TITLE = process.env.COMMIT_TITLE || 'chore(Credits): sync the GitHub contributor list';
const BODY =
  process.env.COMMIT_BODY ||
  '- regenerated by .github/workflows/contributors.yml\n- avatars are self-hosted as WebP under public/images/people/';

if (!TOKEN) throw new Error('缺少 GITHUB_TOKEN');

const git = (...args) => execFileSync('git', args, { encoding: 'utf8' });

/**
 * -z：輸出不加引號跳脫，非 ASCII 路徑照樣拿得到原字串
 * -uall：未追蹤內容逐檔列出；預設會折成一行目錄（`public/images/people/`），拿去讀檔會 EISDIR
 */
function changes() {
  const entries = git('status', '--porcelain=v1', '-z', '-uall').split('\0').filter(Boolean);
  const additions = [];
  const deletions = [];
  for (let i = 0; i < entries.length; i++) {
    const status = entries[i].slice(0, 2);
    const file = entries[i].slice(3);
    if (status[0] === 'R' || status[0] === 'C') {
      // rename／copy 的原路徑是下一個項目；拆成刪舊增新兩筆
      deletions.push({ path: entries[++i] });
      additions.push({ path: file, contents: fs.readFileSync(file).toString('base64') });
      continue;
    }
    if (status.includes('D')) deletions.push({ path: file });
    else additions.push({ path: file, contents: fs.readFileSync(file).toString('base64') });
  }
  return { additions, deletions };
}

const { additions, deletions } = changes();
if (!additions.length && !deletions.length) {
  console.log('沒有改動，不提交');
  process.exit(0);
}

const mutation = `
  mutation ($input: CreateCommitOnBranchInput!) {
    createCommitOnBranch(input: $input) {
      commit { oid url }
    }
  }
`;

const res = await fetch('https://api.github.com/graphql', {
  method: 'POST',
  headers: {
    authorization: `Bearer ${TOKEN}`,
    'content-type': 'application/json',
    'user-agent': 'freshman-contributors-sync',
  },
  body: JSON.stringify({
    query: mutation,
    variables: {
      input: {
        branch: { repositoryNameWithOwner: REPO, branchName: BRANCH },
        message: { headline: TITLE, body: BODY },
        expectedHeadOid: git('rev-parse', 'HEAD').trim(),
        fileChanges: { additions, deletions },
      },
    },
  }),
});

const json = await res.json();
if (!res.ok || json.errors) {
  throw new Error(`createCommitOnBranch 失敗：${JSON.stringify(json.errors ?? json)}`);
}
console.log(
  `已提交 ${additions.length} 增 / ${deletions.length} 刪：${json.data.createCommitOnBranch.commit.url}`,
);
